version: 0.0
os: linux
files:
  - source: ./member-app-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/deploy
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: startup.sh
      runas: root
